### ISSUE TITLE
Fully support ISO 639-1

### ISSUE THREAD

**Issue by shiftpsh** [kyaryunha/MultiLanguage.js#2]
If no language was set by user, this library defaults to system language truncated to 2 characters, resulting 'en-US' and 'en-GB' to be both just 'en', or 'zh-CN' and 'zh-TW' to be both just 'zh'.

**Comment by kyaryunha** [comment]
Thank you for the issue.
I will try to add that feature in October.

It will be updated as follows: 
In the case of "en-US" and "en-GB", try to match "en-us" and "en-gb", and in the case of failure, try to match "en".

**Comment by kyaryunha** [comment]
Hello. Thanks for the good suggestion.
The function has been updated and is supported from version 1.0.7 :)
